= Excel Engine by Quarkus

== Introduction

This project provides an Excel Engine Executor. It loads couple of Excel file (xls, xlsx) and compute all Cells needed.

[![eaas-ci](https://github.com/gautric/excel-as-a-service/actions/workflows/eaas-ci.yml/badge.svg)](https://github.com/gautric/excel-as-a-service/actions/workflows/eaas-ci.yml)

== Run Application 

To run application 

	mvn compile quarkus:dev -Dexcel.static.resouces.uri=../sample

== Call REST API


=== Retrieve all Excel resources available

	curl http://localhost:8080/api

=== Retrieve all Sheet of the Excel resources

	curl http://localhost:8080/api/{resource}

=== Retrieve all Formula from a Sheet of the Excel resources

	curl http://localhost:8080/api/{resource}/{sheet}

=== Compute or Retrieve a Cell Value

	curl http://localhost:8080/api/{resource}/{sheet}/{cell}

== Sample Test


	curl 'http://localhost:8080/api' | jq
	
```
{
  "_count": 1,
  "_self": "http://localhost:8080/eaas/api",
  "results": [
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC",
          "type": "application/json"
        }
      ],
      "name": "KYC",
      "file": "KYC.xlsx"
    }
  ]
}

```


with a KYC sample :

	curl 'http://localhost:8080/eaas/api/KYC' | jq
	
```
{
  "_count": 3,
  "_self": "http://localhost:8080/eaas/api/KYC",
  "results": [
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC",
          "type": "application/json"
        }
      ],
      "name": "ComputeKYC"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/COUNTRY",
          "type": "application/json"
        }
      ],
      "name": "COUNTRY"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/AMOUNT",
          "type": "application/json"
        }
      ],
      "name": "AMOUNT"
    }
  ]
}


```

    curl 'http://localhost:8080/eaas/api/KYC/ComputeKYC'  | jq

```
{
  "_count": 15,
  "_self": "http://localhost:8080/eaas/api/KYC/ComputeKYC",
  "results": [
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/A1",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!A1",
      "value": "",
      "type": "BLANK"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/B1",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!B1",
      "value": "INPUT",
      "type": "STRING"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/C1",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!C1",
      "value": " SCORE",
      "type": "STRING"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/A2",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!A2",
      "value": "PEP",
      "metadata": "@input",
      "type": "STRING"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/B2",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!B2",
      "value": "false",
      "type": "BOOLEAN"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/C2",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!C2",
      "value": "IF(B2,50,0)",
      "type": "FORMULA"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/A3",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!A3",
      "value": "COUNTRY",
      "metadata": "@input",
      "type": "STRING"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/B3",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!B3",
      "value": "FR",
      "type": "STRING"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/C3",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!C3",
      "value": "VLOOKUP(B3,COUNTRY!A1:B5,2,FALSE)",
      "type": "FORMULA"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/A4",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!A4",
      "value": "AMOUNT",
      "metadata": "@input",
      "type": "STRING"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/B4",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!B4",
      "value": 0,
      "type": "NUMERIC"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/C4",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!C4",
      "value": "VLOOKUP(B4,AMOUNT!A1:B5,2,TRUE)",
      "type": "FORMULA"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/A5",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!A5",
      "value": "",
      "type": "BLANK"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/A6",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!A6",
      "value": "FINAL",
      "type": "STRING"
    },
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/C6",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!C6",
      "value": "SUM(C2:C4)",
      "metadata": "@output",
      "type": "FORMULA"
    }
  ]
}
```

    curl 'http://localhost:8080/eaas/api/KYC/ComputeKYC/C6?B2=TRUE&B3=CY&B4=1000000' | jq

```
{
  "_count": 1,
  "_self": "http://localhost:8080/eaas/api/KYC/ComputeKYC/C6?B2=TRUE&B3=CY&B4=1000000",
  "results": [
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/C6",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!C6",
      "value": 125,
      "metadata": "@output",
      "type": "NUMERIC"
    }
  ]
}

```

You can use also POST

    curl -X POST -H "Content-Type: application/json" -d @sample/api_ComputeKYC.json http://localhost:8080/eaas/api/KYC/ComputeKYC/C6


```
{
  "_count": 1,
  "_self": "http://localhost:8080/eaas/api/KYC/ComputeKYC/C6",
  "results": [
    {
      "links": [
        {
          "rel": "self",
          "href": "http://localhost:8080/eaas/api/KYC/ComputeKYC/C6",
          "type": "application/json"
        }
      ],
      "address": "ComputeKYC!C6",
      "value": 125,
      "metadata": "@output",
      "type": "NUMERIC"
    }
  ]
}

```


You can use also POST

    curl -X POST -H "Content-Type: application/json" -d @sample/kafka_ComputeKYC.json http://localhost:8080/eaas/kafka




== Tips for Excel dev

* Include a default value into all Excel cells
** client can retrieve the value
** Excel engine can deal with the type of the cell

* Use only POI implemented functions
** https://poi.apache.org/components/spreadsheet/eval-devguide.html#Appendix+A+%E2%80%94+Functions+supported+by+POI[POI function available list]

== Configuration

.Configuration property
[%header,cols=4*] 
|===

|Properties
|Type 
|Default
|Comments

| `excel.static.resouces.uri`
| String
| `.`
| `classpath://` or _directory_ or _file_

| `excel.return.list.or.map`
| String/Enum
| `MAP`
| Return result into List (`LIST`) or Map(`MAP`)


| `excel.static.readonly`
| boolean
| `false`
| if `true` you cannot use POST method to add new file 

|===


