= Excel Engine by Quarkus

== Introduction

This project provides an Excel Engine Executor. It loads couple of Excel file (xls, xlsx) and compute all Cells needed.



== Run Application 

To run application 

	mvn compile quarkus:dev -Dexcel.static.resouces.uri=../sample

== Call REST API


=== Retrieve all Excel resources available

	curl http://localhost:8080/api

=== Retrieve all Sheet of the Excel resources

	curl http://localhost:8080/api/{resource}

=== Retrieve all Formula from a Sheet of the Excel resources

	curl http://localhost:8080/api/{resource}/{sheet}

=== Compute or Retrieve a Cell Value

	curl http://localhost:8080/api/{resource}/{sheet}/{cell}

== Sample Test

with a KYC sample :

	curl 'http://localhost:8080/api/KYC' | jq
	
```
{
  "_count": 3,
  "_self": "http://localhost:8080/api/KYC",
  "results": [
    {
      "name": "ComputeKYC",
      "_ref": "http://localhost:8080/api/KYC/ComputeKYC"
    },
    {
      "name": "COUNTRY",
      "_ref": "http://localhost:8080/api/KYC/COUNTRY"
    },
    {
      "name": "AMOUNT",
      "_ref": "http://localhost:8080/api/KYC/AMOUNT"
    }
  ]
}

```

    curl 'http://localhost:8080/api/KYC/ComputeKYC'  | jq

```
{
  "_count": 4,
  "_self": "http://localhost:8080/api/KYC/ComputeKYC",
  "results": [
    {
      "address": "C3",
      "formula": "VLOOKUP(B3,COUNTRY!A1:B5,2,FALSE)",
      "_ref": "http://localhost:8080/api/KYC/ComputeKYC/C3"
    },
    {
      "address": "C4",
      "formula": "VLOOKUP(B4,AMOUNT!A1:B5,2,TRUE)",
      "_ref": "http://localhost:8080/api/KYC/ComputeKYC/C4"
    },
    {
      "address": "C6",
      "formula": "SUM(C2:C4)",
      "_ref": "http://localhost:8080/api/KYC/ComputeKYC/C6"
    },
    {
      "address": "C2",
      "formula": "IF(B2,50,0)",
      "_ref": "http://localhost:8080/api/KYC/ComputeKYC/C2"
    }
  ]
}
```

    curl 'http://localhost:8080/api/KYC/ComputeKYC/C6?B2=TRUE&B3=CY&B4=1000000' | jq

```
{
  "_count": 1,
  "_self": "http://localhost:8080/api/KYC/ComputeKYC/C6?B2=TRUE&B3=CY&B4=1000000",
  "results": [
    {
      "address": "C6",
      "value": 125,
      "_ref": "http://localhost:8080/api/KYC/ComputeKYC/C6"
    }
  ]
}
```

== Tips for Excel dev

* Include a default value into all Excel cells
** client can retrieve the value
** Excel engine can deal with the type of the cell


== Configuration

.Configuration property
[%header,cols=4*] 
|===

|Properties
|Type 
|Default
|Comments

| `excel.static.resouces.uri`
| String
| `.`
| `classpath://` or _directory_ or _file_

| `excel.return.list.or.map`
| String/Enum
| `MAP`
| Return result into List (`LIST`) or Map(`MAP`)


| `excel.static.readonly`
| boolean
| `false`
| if `true` you cannot use POST method to add new file 

|===


