name: eaas-ci-matrix

on: [push]

jobs:
  build:
    strategy:
      matrix:
        version: [17,21]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'adopt-openj9'
      - name: Build with Maven ${{ matrix.version }}
        run: mvn --batch-mode --update-snapshots verify